# base image is missing some requirements for the detectron2 install
ARG CUDA_VERSION=10.1
FROM ohjho/py37_cuda:${CUDA_VERSION}

LABEL maintainer="ohjho <john@miro.io>"

# basic requirements: PyTorch + pycocotools
RUN pip install tensorboard cython
RUN pip install torch==1.5+cu101 torchvision==0.6+cu101 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install pycocotools>=2.0.1

# install detectron2
ARG DETECTRON2_VERSION=0.1.3
RUN git clone -b v${DETECTRON2_VERSION} https://github.com/facebookresearch/detectron2 detectron2_repo
# set FORCE_CUDA because during `docker build` cuda is not accessible
ENV FORCE_CUDA="1"
# This will by default build detectron2 for all common cuda architectures and take a lot more time,
# because inside `docker build`, there is no way to tell which architecture will be used.
ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"

RUN pip install --user -e detectron2_repo

# Run the script to show Detection2 Environments
RUN python -m detectron2.utils.collect_env
